name: base
channels:
  - conda-forge
  - pyviz
  - defaults
dependencies:
  - _libgcc_mutex
  - _openmp_mutex
  - aiohttp
  - alembic
  - anyio
  - argon2-cffi
  - async-timeout
  - async_generator
  - attrs
  - babel
  - backcall
  - backports
  - backports.functools_lru_cache
  - bleach
  - blinker
  - bokeh
  - brotlipy
  - c-ares
  - ca-certificates
  - certifi
  - certipy
  - cffi
  - chardet
  - click
  - cloudpickle
  - colorama
  - conda
  - conda-package-handling
  - configurable-http-proxy
  - cryptography
  - curl
  - cytoolz
  - dask
  - dask-core
  - dask-labextension
  - dask_labextension
  - decorator
  - defusedxml
  - deprecation
  - distributed
  - entrypoints
  - flake8
  - freetype
  - fsspec
  - gitdb
  - gitpython
  - greenlet
  - heapdict
  - icu
  - idna
  - importlib-metadata
  - ipykernel
  - ipython
  - ipython_genutils
  - jbig
  - jedi
  - jinja2
  - jpeg
  - json5
  - jsonschema
  - jupyter-packaging
  - jupyter-resource-usage
  - jupyter-server-mathjax
  - jupyter-server-proxy
  - jupyter_client
  - jupyter_core
  - jupyter_server
  - jupyter_telemetry
  - jupyterhub
  - jupyterhub-base
  - jupyterlab
  - jupyterlab-git
  - jupyterlab-mathjax3
  - jupyterlab-nvdashboard
  - jupyterlab-recents
  - jupyterlab-variableinspector
  - jupyterlab_pygments
  - jupyterlab_server
  - krb5
  - lcms2
  - ld_impl_linux-64
  - lerc
  - libblas
  - libcblas
  - libcurl
  - libdeflate
  - libedit
  - libev
  - libffi
  - libgcc-ng
  - libgfortran-ng
  - libgfortran5
  - libgomp
  - liblapack
  - libmemcached
  - libnghttp2
  - libopenblas
  - libpng
  - libsodium
  - libssh2
  - libstdcxx-ng
  - libtiff
  - libuv
  - libwebp-base
  - locket
  - lz4-c
  - mako
  - markupsafe
  - matplotlib-inline
  - mccabe
  - mistune
  - msgpack-python
  - multidict
  - nb_conda_kernels
  - nbclassic
  - nbclient
  - nbconvert
  - nbdime
  - nbformat
  - ncurses
  - nest-asyncio
  - nodejs
  - notebook
  - numpy
  - oauthlib
  - olefile
  - openjpeg
  - openssl
  - packaging
  - pamela
  - pandas
  - panel
  - pandoc
  - pandocfilters
  - parso
  - partd
  - pexpect
  - pickleshare
  - pillow
  - pip
  - prometheus_client
  - prompt-toolkit
  - psutil
  - ptyprocess
  - pycodestyle
  - pycosat
  - pycparser
  - pycurl
  - pyflakes
  - pygments
  - pyjwt
  - pynvml
  - pyopenssl
  - pyparsing
  - pyrsistent
  - pysocks
  - python
  - python-dateutil
  - python-editor
  - python-json-logger
  - python_abi
  - pytz
  - pyviz_comms
  - pyyaml
  - pyzmq
  - readline
  - requests
  - ruamel.yaml
  - ruamel.yaml.clib
  - ruamel_yaml
  - send2trash
  - setuptools
  - simpervisor
  - six
  - smmap
  - sniffio
  - sortedcontainers
  - sqlalchemy
  - sqlite
  - sudospawner
  - tblib
  - terminado
  - testpath
  - tk
  - tomlkit
  - toolz
  - tornado
  - tqdm
  - traitlets
  - typing-extensions
  - typing_extensions
  - tzdata
  - urllib3
  - wcwidth
  - webencodings
  - websocket-client
  - wheel
  - xz
  - yaml
  - yarl
  - zeromq
  - zict
  - zipp
  - zlib
  - zstd
  - pip:
    - asyncssh
    - wrapspawner
